version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8077:8077"
    env_file:
      - .envs/.postgres
    depends_on:
      - db
  db:
    image: ankane/pgvector
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .envs/.postgres
  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - app
